#!/bin/bash
sbatch bash/ML_BH_FW_0.sh
sbatch bash/ML_BH_FW_1.sh
sbatch bash/ML_BH_FW_2.sh
sbatch bash/ML_BH_FW_3.sh
sbatch bash/ML_BH_FW_4.sh
sbatch bash/ML_BH_FW_5.sh
sbatch bash/ML_BH_FW_6.sh
sbatch bash/ML_BH_FW_7.sh
sbatch bash/ML_BH_FW_8.sh
sbatch bash/ML_BH_FW_9.sh
sbatch bash/BH_FW_0.sh
sbatch bash/BH_FW_1.sh
sbatch bash/BH_FW_2.sh
sbatch bash/BH_FW_3.sh
sbatch bash/BH_FW_4.sh
sbatch bash/BH_FW_5.sh
sbatch bash/BH_FW_6.sh
sbatch bash/BH_FW_7.sh
sbatch bash/BH_FW_8.sh
sbatch bash/BH_FW_9.sh
