#!/bin/bash
sbatch bash/BH_FW_0.sh
sbatch bash/BH_FW_1.sh
sbatch bash/BH_FW_2.sh
sbatch bash/BH_FW_3.sh
sbatch bash/BH_FW_4.sh
sbatch bash/BH_FW_5.sh
sbatch bash/BH_FW_6.sh
sbatch bash/BH_FW_7.sh
sbatch bash/BH_FW_8.sh
sbatch bash/BH_FW_9.sh
sbatch bash/BH_FW_10.sh
sbatch bash/BH_FW_11.sh
sbatch bash/BH_FW_12.sh
sbatch bash/BH_FW_13.sh
sbatch bash/BH_FW_14.sh
sbatch bash/BH_FW_15.sh
sbatch bash/BH_FW_16.sh
sbatch bash/BH_FW_17.sh
sbatch bash/BH_FW_18.sh
sbatch bash/BH_FW_19.sh
sbatch bash/BH_FW_20.sh
sbatch bash/BH_FW_21.sh
sbatch bash/BH_FW_22.sh
sbatch bash/BH_FW_23.sh
sbatch bash/BH_FW_24.sh
